// Generated by gencpp from file ieskf_slam/CloudWithPose.msg
// DO NOT EDIT!


#ifndef IESKF_SLAM_MESSAGE_CLOUDWITHPOSE_H
#define IESKF_SLAM_MESSAGE_CLOUDWITHPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <geometry_msgs/Pose.h>

namespace ieskf_slam
{
template <class ContainerAllocator>
struct CloudWithPose_
{
  typedef CloudWithPose_<ContainerAllocator> Type;

  CloudWithPose_()
    : pointcloud()
    , pose()  {
    }
  CloudWithPose_(const ContainerAllocator& _alloc)
    : pointcloud(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_type;
  _pointcloud_type pointcloud;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::ieskf_slam::CloudWithPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ieskf_slam::CloudWithPose_<ContainerAllocator> const> ConstPtr;

}; // struct CloudWithPose_

typedef ::ieskf_slam::CloudWithPose_<std::allocator<void> > CloudWithPose;

typedef boost::shared_ptr< ::ieskf_slam::CloudWithPose > CloudWithPosePtr;
typedef boost::shared_ptr< ::ieskf_slam::CloudWithPose const> CloudWithPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ieskf_slam::CloudWithPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ieskf_slam::CloudWithPose_<ContainerAllocator1> & lhs, const ::ieskf_slam::CloudWithPose_<ContainerAllocator2> & rhs)
{
  return lhs.pointcloud == rhs.pointcloud &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ieskf_slam::CloudWithPose_<ContainerAllocator1> & lhs, const ::ieskf_slam::CloudWithPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ieskf_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ieskf_slam::CloudWithPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ieskf_slam::CloudWithPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ieskf_slam::CloudWithPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3540d68841825d41de92c8a4368f472f";
  }

  static const char* value(const ::ieskf_slam::CloudWithPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3540d68841825d41ULL;
  static const uint64_t static_value2 = 0xde92c8a4368f472fULL;
};

template<class ContainerAllocator>
struct DataType< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ieskf_slam/CloudWithPose";
  }

  static const char* value(const ::ieskf_slam::CloudWithPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2 pointcloud\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ieskf_slam::CloudWithPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointcloud);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CloudWithPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ieskf_slam::CloudWithPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ieskf_slam::CloudWithPose_<ContainerAllocator>& v)
  {
    s << indent << "pointcloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IESKF_SLAM_MESSAGE_CLOUDWITHPOSE_H
